#!/system/bin/sh

cp -f /system/etc/ril_config /data/misc/ril_config
chmod 0660 /data/misc/ril_config
chown root:radio /data/misc/ril_config
cp -f /system/etc/psdata/sterc_conf /data/misc/psdata/sterc_conf
cp -f /system/etc/psdata/sterc_script_connect /data/misc/psdata/sterc_script_connect
cp -f /system/etc/psdata/sterc_script_disconnect /data/misc/psdata/sterc_script_disconnect
cp -f /system/etc/psdata/sterc_conf_alt /data/misc/psdata/sterc_conf_alt
cp -f /system/etc/psdata/sterc_script_connect_alt /data/misc/psdata/sterc_script_connect_alt
cp -f /system/etc/psdata/sterc_script_connect_dun /data/misc/psdata/sterc_script_connect_dun
cp -f /system/etc/psdata/sterc_script_disconnect_dun /data/misc/psdata/sterc_script_disconnect_dun
chmod 0660 /data/misc/psdata/sterc_conf
chmod 0500 /data/misc/psdata/sterc_script_connect
chmod 0500 /data/misc/psdata/sterc_script_disconnect
chmod 0660 /data/misc/psdata/sterc_conf_alt
chmod 0500 /data/misc/psdata/sterc_script_connect_alt
chmod 0500 /data/misc/psdata/sterc_script_connect_dun
chmod 0500 /data/misc/psdata/sterc_script_disconnect_dun
chown root:radio /data/misc/psdata/sterc_conf
chown root:radio /data/misc/psdata/sterc_conf_alt
cp -f /system/etc/psdata/stepscc_conf /data/misc/psdata/stepscc_conf
chmod 0660 /data/misc/psdata/stepscc_conf
chown root:radio /data/misc/psdata/stepscc_conf
